name: Publish Package to Verdaccio
on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: ${{ secrets.VERDACCIO_HOST }}
      - run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}
      - run: npm run build --if-present
      - run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.VERDACCIO_TOKEN }}

